name: admin
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  shelf: ^1.4.1
  go_router: ^14.2.8
  window_manager: ^0.4.2
  sqflite: ^2.3.3+1
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  qr_flutter: ^4.1.0
  web_socket_channel: ^3.0.1
  shelf_web_socket: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  riverpod_generator: ^2.4.3
  build_runner: ^2.4.12
  custom_lint: ^0.6.7
  riverpod_lint: ^2.3.13
  flutter_launcher_icons: ^0.14.1

flutter:
  uses-material-design: true
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
flutter_launcher_icons:
  windows:
    generate: true
    image_path: "assets/icon/icon.jpg"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.jpg"